# Model Hyperparameters
latent_dim: 256 # Dimension of the latent vector z
batch_size: 128 # Batch size for training
lr: 0.0001 # Learning rate for Adam optimizer

# Loss Weights
lambda_d: 1.0 # Weight for Discriminator loss
lambda_e: 1.0 # Weight for Adversarial Encoder loss
recon_weight: 1.0 # Weight for Reconstruction loss


# Training Loop
epochs: 200 # Number of epochs to train


#weighted loss parameters
alpha_vpo: 10.0 # Weight factor for velocity pointwise loss